### ISSUE TITLE
Add the env settings to the default file.

### ISSUE THREAD

**Issue by azak1r** [revenantal/eve-operations#1]
Add 
'''
EVEONLINE_CLIENT_ID=
EVEONLINE_CLIENT_SECRET=
EVEONLINE_REDIRECT=
'''

To the example.env file so it would become as easy as a simple copy and rename of the file for each installation.

**Comment by crazyjoery** [comment]
https://github.com/revenantal/eve-operations/commit/710ed4ff33a67e72c612e9bf1e7e1f21c74f6d71
